### ISSUE TITLE
Don't support danish "Æ Ø Å"

### ISSUE THREAD

**Issue by MumiNett** [M0dEx/FunQuiz#6] opened 2020-03-16 18:52 UTC
I found this causing, problems with the danish letters, it makes "?" insted

**Comment by M0dEx** [comment] 2020-03-29 21:06
The issue is fixed by including the `-Dfile.encoding=UTF-8` argument in the server start up file on Windows. Seems to be an issue with the Java 8 for Win.

**Closed as completed by M0dEx** 2020-03-29 21:06 UTC
Labels: bug
